##
##  Makefile -- Build procedure for sample csv_to_html Apache module
##  Autogenerated via ``apxs -n csv_to_html -g''.
##

builddir=.
top_srcdir=/opt/homebrew/opt/httpd
top_builddir=/opt/homebrew/opt/httpd
include /opt/homebrew/opt/httpd/lib/httpd/build/special.mk

#   the used tools
APACHECTL=apachectl

#   additional defines, includes and libraries
#DEFS=-Dmy_define=my_value
#INCLUDES=-Imy/include/dir
#LIBS=-Lmy/lib/dir -lmylib

#   the default target
all: local-shared-build

#   install the shared object file into Apache 
install: install-modules-yes

#   cleanup
clean:
	-rm -f mod_csv_to_html.o mod_csv_to_html.lo mod_csv_to_html.slo mod_csv_to_html.la 

#   simple test
test: reload
	lynx -mime_header http://localhost/csv_to_html

#   install and activate shared object by reloading Apache to
#   force a reload of the shared object file
reload: install restart

#   the general Apache start/restart/stop
#   procedures
start:
	$(APACHECTL) start
restart:
	$(APACHECTL) restart
stop:
	$(APACHECTL) stop

