name: Build Apache Module
permissions:
  contents: write
  actions: read
on:
  push:
    branches:
      - 'main'
      - 'releases/**'


jobs:
  build-linux:
    name: Build for Linux
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Install dependencies
        run: |
          sudo apt update
          sudo apt install -y apache2-dev apache2-utils build-essential

      - name: Build module
        run: |
          apxs -c mod_csv_to_html.c csv_reader.c
          mkdir -p build
          ls -la
          mv .libs/*.so build/

      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: linux-module
          path: build/mod_csv_to_html.so


  release:
    needs: [build-linux]
    name: Create Release
    runs-on: ubuntu-latest

    steps:
      - name: Download Linux module artifact
        uses: actions/download-artifact@v4
        with:
          name: linux-module
          path: artifacts
      - name: Zip file
        run: cd  ${{ github.workspace }}/artifacts && zip mod_csv_to_html.zip mod_csv_to_html.so
      - name: Display structure of downloaded files
        run: |
          ls
          echo "======"
          pwd
          echo "======"
          ls ${{ github.workspace }}
          echo "======"
          tree ${{ github.workspace }}
          echo "======"
      - name: Create GitHub Release
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          asset_path:  ${{ github.workspace }}/artifacts/mod_csv_to_html.zip
          asset_name: 'Apache module'
          upload_url: ${{ steps.create_release.outputs.upload_url }}
          asset_content_type: 'application/zip'
