name: Build Apache Module
permissions:
  contents: write
  actions: read
on:
  push:
    tags:
      - "v*"

jobs:
  build-linux:
    name: Build for Linux
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Install dependencies
        run: |
          sudo apt update
          sudo apt install -y apache2-dev apache2-utils build-essential

      - name: Build module
        run: |
          apxs -c mod_csv_to_html.c csv_reader.c
          mkdir -p build
          ls -la
          mv .libs/*.so build/

      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: linux-module
          path: build/mod_csv_to_html.so


  release:
    needs: [build-linux]
    name: Create Release
    runs-on: ubuntu-latest

    steps:
      - name: Download Linux module artifact
        uses: actions/download-artifact@v4
        with:
          name: linux-module
          path: artifacts
      - name: Display structure of downloaded files
        run: ls -R artifacts
      - name: Create GitHub Release
        uses: AButler/upload-release-assets@v3.0
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          repo-token: ${{ secrets.GITHUB_TOKEN }}
          files: 'artifacts/*'
          release-tag: ${{ github.ref_name }}
