name: Build Apache Module
permissions:
  contents: write
  actions: read
on:
  push:
    tags:
      - "v*"

jobs:
  build-linux:
    name: Build for Linux
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Install dependencies
        run: |
          sudo apt update
          sudo apt install -y apache2-dev apache2-utils build-essential

      - name: Build module
        run: |
          apxs -c mod_csv_to_html.c csv_reader.c
          mkdir -p build
          mv .libs/*.so build/

      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: linux-module
          path: build


  release:
    needs: [build-linux,]
    name: Create Release
    runs-on: ubuntu-latest

    steps:
      - name: Download Linux module artifact
        uses: actions/download-artifact@v3
        with:
          name: linux-module
          path: release/linux

      - name: Create GitHub Release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: ${{ github.ref_name }}
          release_name: "Release ${{ github.ref_name }}"
          draft: false
          prerelease: false
          body_path: build/mod_csv_to_html.so
